[package]
name = "mc_turbojet"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mc_turbojet"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
